accessing
code
	^ 'xmi_id,cls_name
5,"FLASH MEMORY ARRAYPAGE 5121528 BYTES"
6,"RASH MEMORY ARRAYPAGE 5121528 BYTES"
14,ParamSet
14,"GraphNode 1"
14,Element
14,Circuit
14,Model
14,Xsubckt
14,Terminal
14,SubCircuit
14,OutRequest
14,InternalTerminal
14,ParamError
14,CircuitError
29,ClassifyWorker
29,key—>inheritance—*awareness
29,EMPTY
29,EMPTY
29,LoadWorker
29,EMPTY
29,SaveWorker
29,DrawWorker
29,"TwoDeeOvervi ew"
29,Profile
29,Worker
29,"Sel ec tionBox"
29,BoxOverlay
29,LagDisplay
31,EMPTY
31,Event
32,EMPTY
32,Category
32,Thread
32,Post
33,EMPTY
33,"name Stringicon Stringdescription Stringun String"
34,EMPTY
34,Guide
35,EMPTY
35,Message
37,TosfComponnt
37,TostCase
37,TestSuito
38,EMPTY
38,FunctionHandleTestCase
39,"I TestRunMonitor I"
39,TestRunLogger
39,CommandWindowTestRunDisplay
48,"Deac onObservable"
48,"interfaceDeac o nO bs erver"
48,onPushDeaconResponseonErrorDeaconErroronReconnect
48,Runnable
48,DeaconService
48,DeaconRunnable
48,"data cIassSubscription"
48,Deacon
48,"UserAp p"
48,Message
50,botprint
50,Canvas2D
50,Preview3D
50,ellipseHandler
50,circieHandler
50,rectangIeHan’d1
50,"freeshapeHan die r"
50,editHandler
50,resizer
50,rotator
50,remover
50,"abstractDrawHandler I"
50,EMPTY
55,joueur
55,"Station de recherche"
55,Cite
55,"Carte Infection"
55,Role
55,Equipe
55,"Carte joueur"
55,Pandémie
55,"Pile de carte"
55,"Carte Epidemie"
55,"Carte Spéciale"
55,Maladie
55,"Liste de cartes défausses"
55,EMPTY
55,EMPTY
56,DataCache
56,"I Model"
56,EMPTY
56,DataConverterService
56,interfacelExtendedVersionHandler
56,SolverService
56,EMPTY
56,"OutputSou rceCodeService"
56,UserSelectablePolynomial
56,UserDefinedFunction
56,Spline
56,EMPTY
56,EMPTY
56,EMPTY
56,"UserSelectablePolyration al"
70,"Tetherball LLC"
70,Links
70,EMPTY
70,SMS
70,"7Digit Numeric String"
70,EMPTY
70,"ReceiverWants to Opt4nhas no app"
70,TetherballcEic
75,DProperty
75,KnownProperty
75,UnknownProperty
75,CirPropertyBase
75,PhpField
75,PhpPropertypositionoverridesimplements
75,CirProperty
75,CirField
75,CirEvent
75,PhpFieldBuilder
75,PhpPropertyBuilder
96,"WebAppi i cciti. on"
96,MyWebApplication
96,"Appli cationContextAware"
115,FormComponentl
115,"e TextFieLdl"
115,"0 Button 1"
115,"e TextArea 1"
115,"DropDownChoice 1"
116,Root
116,EMPTY
116,EMPTY
116,EMPTY
116,EMPTY
116,EMPTY
116,EMPTY
116,EMPTY
119,EMPTY
119,EMPTY
119,"• _ded deck• flayer_hand blackjack_han&• _dealer_hand blackjack_hand"
119,"• _deck 1 deck jIayer_hand  beggar_flan&• _deaer_hand beg9ar_hand• _acive_hand  beqgar_hand _discard_hand d&ard_hand* penaky_cards nt"
119,EMPTY
119,"S _cards stdvecor<card’>S score mt"
119,"deck I"
119,"discard hand"
119,card
119,.ccenum>>suit
119,<<enurn>rank
120,"UNKNOWNT pueq aupeUNKNOWNT  puq aeap"
120,EMPTY
120," _deck deckjIayer hand b1ackackhand _dealer_hand blackjack_hand"
120," _deck deck• p’ayer_hand beggar_han&• _deaer_hand bggar_hanc1• _acIve_hand  beqgar_hand* discard_hand discard hand’ penaIy cards nt"
120,EMPTY
120,card_hand
120,deck
120,EMPTY
120,EMPTY
120,suit
120,<<enumrank
126,"d I arat ion"
127,"code interactiveinterpreter I"
127,"code interactiveConsole"
127,"SimpIeR EPL"
128,SRAdzlress
129,"SBAttachl nfo"
130,EMPTY
131,ranges_access
132,SBBreakpoint
133,SflflreakpointLacation
134,SBBroa±aster
135,"SBCommandl nterpreter"
136,"SBCommunic at ion"
137,"SBCompiIeU nit"
138,"SBD at a"
139,SBDebuer
140,SRDeclaration
141,EMPTY
142,EMPTY
143,SRExpressionOptions
144,SBFiIeSpec
145,"SRFiIeSpec List"
146,EMPTY
147,SRFunction
148,"SRH ostOS"
149,"SBInputR eader"
150,SBlnstruction
151,"SBI nstructionList"
152,"SBLaunchl nfo"
153,SBLineEntry
154,SBListener
155,SRMcduIe
156,compile_units_access
157,re_compileJype
158,"SflModuleSpec List"
159,SBProcess
160,SBSection
161,SBSourceManager
162,SBStringList
163,SBSymboI
164,SBSymbolContextList
165,SBTarget
166,SRTypeList
167,S9TypeMember
168,SBTypeNameSpecifier
169,SBTypeSummary
170,SBTypeSynthetic
171,SBThread
172,EMPTY
173,SBTypeCategory
174,formatters_access_class
175,SBTypeFilter
176,"SBVaIue I"
177,value
605,"<<Java Class>>OWizardElectricalSetupinverterscom.aronyrni.5oI3r.r4rod"
605,"<<Java Class>>G Inverterinformation Serviceoom.aronymots.soIar.cliert"
605,"<<Java Class>>GWizardElectricalcomaronymous soar.arro"
605,"<<Java Class>>ecom.arorymous.otar.shared"
605,"<<Java Class>>SolarAlertDialog"
606,"<<Java Class>>GWizardLocationom.arnymo. 3r.arroa"
606,"<<Java Class>>Location DataExceptioncon a oryn ua. soLar. shar€"
606,"<<Java Class>>G LocationListenerimpi"
606,"<<Java Cass>>O SolarAlertDialogcom.anonymoLr3. soL3r.andro"
606,"<<Java Class>>GWizardLocationltemOverlaycom.aror.ymos.soar.arbdro"
606,"<<Java Class>>LocationDataoorn.aronynoLs.s1sr. shre"
606,"<<Java Class>>e WizardLocation SetupLocationscomaronyroLis.olar.3rdroi"
606,"<<Java Class>>Locationlnformation Servicecom.aronymous.oLar.chent"
607,"<<Java Class>>SolarpanelExceptioncom.arorynous.sr.stre"
607,"<<Java Class>>ocom.aronyrno. sr.andro"
607,"<<Java Class>>G SolarAlertDialogom.aonys.r.arro"
607,"<<Java Class>>0 SolarPanelcomaronymous. sor.sar"
607,"<<Java Class>>sensorEventHandlercornaronymouoI3r.arro"
607,"<<Java Class>>GWizardPanelSetupPanelscon .aronyrnoLs.oL3r.ar.rc"
607,"<<Java Class>>O SolarPanelscom.ar.yns.soar.shar"
607,"<<Java Class>>3 Panelinformation Serviceoorn.aronyrnoLs. scarchent"
607,"<<Java Class>>G SolarPanelsExceptioncon.anorymous. solar. ssrso"
608,"<<Java Ctass>>WizardResuIts"
608,"<<Java Class>>ecom.aronymots.ar.cbnt"
608,"<<Java Class>>O SolarSetupExceptioncon’ .aronyrnos. soar.share"
608,"<<Java Class>>WizardResuItsGetResuItscoma ymou 1ar.rrc"
608,"<<Java Class>>SoIarAIertDiaIogoom.aronymoLs. r.arro"
608,"<<Java Class>>I e SolarSetupcorTtanonymou3.sar.sh3re"
608,"<<Java Class>>WizardResLuItGraph"
608,"<<Java Class>>WizardResuItsComparisoncorn.aror.ymous .soL3r.ardro"
608,"<<Java Class>>SolarResultExceptionoom.amonyrrous.sar. st3re"
608,"<<Java Class>>SolarResultcom.aronyrnoLs.soIar. shared"
609,"<<Java Class>>eWizardTaiiucom.anonymous. soLar.arro"
609,"<<Java Class>>G CustomerDataoom.anonynous.sIar. st’3r"
609,"<<Java Class>>SolarAlertDialogcon.arym.ar.ardro"
609,"<<Java Class>>OWizardTariltSetupTariftcom.arorynous.soL3r.arbdro"
609,"<<Java Class>>3 TariffRatecorn. ironyrno. solar. alarec"
609,"<<Java Class>>Tarifflnformation Servicern .arorynoLs.soIar.cent"
609,"<<Java Class>>e TarifiRateExceptioncom.aronyrnoL5"
633,User
633,Teachinqilanager
633,Teacher
633,Student
633,UserManaqer
633,Teaches
633,EMPTY
633,Classlianaqer
633,EMPTY
633,Enrolment
633,Enrolmentilanager
647," tontrolleri) — Controller StartlinFile string. outFile string) actionAddToCart actionRemoveFromCart actionViewCart actionListltems actionCheckout actionShowShopltems actionAddCopiestoltem actionChangeltemCost actionAddnewUser Login))  bool"
647," snopi — shop getltems addltemitem  Item*"
647," Modelt) — Modell) addToCartItem ltem* removeFromCartlltem  Item*) getShoppingCartltems tryUpdateShopltemitem  Item*. isEversion  bool getUserild string) User* addUserluser User) getShopltemsl) vector< Item * getShopltemslcontainsTitle  string*)  vec"
647," Viewl) — View showSbopperMenushopper string showAdminMenuladmin  string)  mt showLoginMenu getinputi.)  string writeMessagemessage  string& selectltemitemList  vector< Item * >* getsearchltemi)  string numberlnputmessage  string mm  mt. max  int Iis"
647," shoppIngcarti — Shoppingcart getltems getSum getSpendingLimit setSumsum double setSpendingLimitlimit double addltemitem Item"
647," Useri) — User setldid  string setPasswordpassword  string setNamename string setEmailemail string setTypeltype ShopperType) setMemberisMember bool getld getPassword getName getEmail getTypel) ShopperType getMember getShoppingcart operator >>.stream "
647," OOkU BookTitle  string Author string. hasEbook  bool StockQty int BookTitle  string Author string. hasEbook  bool StockQty mt. pPrice  double. ePrice  double Book getAuthor setAuthorAuthor string* operator >>.is  istream&. obj  Book& operator <<os  "
647," r1usIci MusicTitle  string Artist string. hasEmusic  bool. StockQty int MusicTitle  string Artist string. hasEmusic  bool. StockQty mt. pPrice  double. ePrice  double Music getArtist setArtistArtist string* operator >>.is  istream&. obj  Music& oper"
647," lIIerarseIxceptPonLmsg  const strlngat) FileparseException what"
647," frIIeNotounabxceptIonims9 const strInga) — FileNotFoundException what"
687,Account
687,Triisaclion
687,Product
687,Person
687,Address
687,EMPTY
687,"ManagedFund I"
687,"Cash 1"
726,"Co mponentlm p11"
726,Component
726,"Old Inheritance Tree"
726,"Co mponentlm p12"
726,Building
726,"Corn po n e ntH older"
726,Unit
736,<<Interface>>
736,CalService
736,EMPTY
736,"GetEventsCalendar Time Period)(CreateEventCalendar Event)(CreateCalendarCalendar)("
736,Controller
736,MainView
736,Event
736,EMPTY
736,GetCalendarServicesGetListOfCalendars
736,Show
736,EMPTY
756,"Disabler widget"
756,"Search widget"
756,"Tabs widget"
756,"History widget"
756,"Search Resufts widget"
770," cdUsuatio nmUsuario seriha tpUsuatio• dtlndusae dtAtuelizacae• cdOpedndusao cdOpeiAtualizacsomtStringStringmtDateDatemtmt"
770," cdEquipanento dsEquipanento TpEquipanento dsMarcaEquip dsAtribEquip ruSsia nrPredio dtindusao diAtusiizacao cdOperindusao cdOpecAtuaiizacaontStingntSUingStrtingntntDateDatentnt"
770,"• cdTpUso nmTpUsu• dtlndusao• dtAtualizacao• cdOpedncJusao cdOpeiAtualizacaomtStringDateDatemtmt"
770," cdTurrma* nmTurrna cdDisiplina cdPrefessv• dtlndusae• dtAtu8lizacao• cdOpedndusao• cdOperAtualizaceoStringmtmtDateDatemtmtmt"
770,"• cdTurrna cdDsciplina• cd4oario• dtlndusao dtAtuslizacao cxOperIndusae cdOperAtualizacsomtmtmntDateDatemntmnt"
770,"Itereserva I"
770," aReseiva ResponsaveI dsOcotrencia status nrPrediouso nrSalaUso dtlnicioRes dtPrevDev dtDevolucao dtlndusao dtAtualizacao cdOpetlnclusao cdOpetAtualizacaontmtSffingmtntntDateDatentDateDatentnt"
770,)cario
770,Disciplina
776,"<<s in q I et on>>D at aS o u rc eM an age r"
776,".<interface>>ID t aS a u rc e Paxm et e rs"
776,". <I nt e rface>ID t aSou rc e"
776,"<<Interface>>ID at aSt a re Param et ers"
776," < i nt e riac e>>Observable"
776,"<.d nt en ate>>lDataStore"
776,"i nt e riac e>>ID at aC o lie ct io n"
776,"nt erfate>>It e rat or"
776,"<i nt eniate>>Collection"
776,EMPTY
780,Voiture
780,Client
780,ClientAdapter
780,DataFabrication
780,DatarMianager
780,VoitureAdapter
781,ClientActivity
781,SérialisationClientvehicule
781,Client
781,Park.Voiture
781,Fabrication
781,Parck’ehicuIe
781,VehiculeAdapter
781,"DataClientVehicu I e"
788,"<<Java Class>>G MaConsoleUNKNOWNdefault package"
788,"<<Java Enumeration>>o NameUNKNOWNdefauh package"
788,"<<Java Enumeration>>OTartineUNKNOWNdefault package"
788,"<<Java Class>>e ErratiqueUNKNOWNdefault pa&age"
788,"ErratiqueString CaseLofLo seDepIacervoIdo mangerCommestibleo cycleDeVleOvoldo dessinerObjetGraphics"
788,"<<Java Class>>E CommestibleUNKNOWNdefau’t package"
788,"<<Java Class>>GSa iso n 1UNKNOWNdefault package"
788,"dCommestible• donneEnergieNeuneu0 getEnergie"
788,"<<Java Class>>€NeuneuUNKNOWNdefault pa&age"
788,"<<Java Class>>Vo raceUNKNOWNdefault package"
788,"EVoraceStnng CaseLofL• seDepIacervoido mangerCommestible• dessnerObjetGraphcs"
788,"<<Java Class>>GLapinUNKNOWNdefault package"
788,"<<Java Class>>CannibaIeUNKNOWNdefault package"
788,"dbpinString CaseLoft• sebeplacerOvold• mangeiCommestibIe• cycleoeVièQvoidQ dessinerObjetGaphics"
788,"dcannibaleStringCaseLofto seDeplacerOvold‘ mangerCommestiblek cycleDeVleOvold\Q’1essinerObJetGraphIcs"
788,"<<Java Class>>GLoftUNKNOWNdefault package"
788,"<<Java Class>>G LoftPanelUNKNOWNdefault package"
788,"<<Java Class>>GCaseUNKNOWNdefault package"
788,"<<Java Class>>0 ZoneGraph iq ueUNKNOWNdefault padage"
788,ELoftPanelLinkedList<ObjetDessinable>
788,"<<Java Class>>G NourritureUNKNOWNdefault package"
788,"<<Java Interface>>O ObjetDessinableUNKNOWNdefau’t package"
788,"o dessinerObjetGraphics"
795,Article
795,EMPTY
795,EMPTY
795,Shoppinglist
795,Store
795,Purchasehistory
801,"NOTE1. Relations between business logicand persistent object were notmarked in the diagram.2. Classes with yellow background are not actuallyphp classes but common php script files.3. The brief order of dependency in add.phpand edit.php has been mark"
801,ezcomFormTool
801,ezcomAddCommentTool
801,ezcomEditCommertTooI
801,EMPTY
801,ezcomCookieManger
801,edit.php
801,ezcomCommentManager
801,"ezcomPermi ss ion"
801,delete.php
801,ezcomUtility
801,ezcomCommonCommentManager
801,ezcomSubscriptionManager
801,activate.php
801,cronjob—ezcomclearsubscription.php
801,eZPersistentObject
801,cronjob—ezcomhandlenotification.php
801,ezcomNotificationManager
801,ezcomComment
801,ezcomSubscriber
801,ezcomSubscription
801,ezcomNotification
801,ezcomNotificationEmaAlManager
808,"orti. apache.tools. ant.types.DataType"
808,ImeqeOperetion
808,"Trans formOeration"
808,BesicShepe
808,Text
808,Draw
808,Scale
808,Arc
808,Rotate
808,Rectancile
808,Ellipse
808,ColorMapper
808,EMPTY
813,CalenderOverview
813,Event
813,Calender
813,Message
813,User
813,Invitation
813,<<Enum>Response
814,Assignmentl
814,Environment
814,View
814,Position
814,<<Agent>>
814,PredatorPolicyEvaluation
814,"Prey I"
814,EMPTY
814,PredatorRand4m
814,EMPTY
814,PredatorPolicyEvaluationNewRep
814,PredatorPolicylteration
814,PolicyiterationPart
814,PredatorValuelterationNewRep
814,StateRepresentation
815,Assigriment2
815,Environment
815,View
815,StateRepresentation
815,Position
815,<<Agent>>
815,Prey
815,PredatorQLearning
815,PredatorOnPolicy
815,Predatoroffpolicy
816,EMPTY
816,EMPTY
816,EMPTY
825,rndfs.cIienLapLFiIeQueIy
825,mdfs.clientparser.JSONHeaderCreator
825,"mclfs.LIhIs.io.SockelF unchons"
825,mdfs.uhls.io.SockelFactory
825,"mdfs.clientapi.FiIeQ uerylmpl"
825,nldfs.LIUIs.parser.FileNameOperalions
826,nidfs.uliIs.Verbose
826,"mdfs. ulils.Conhg"
826,mdfs.datanode.io.ConnechonListener
826,"mclfs.LIhIs.io.SockelF unchons"
826,mdfs.datanode.Eo.ConnechonSheppard
826,mdfs.uhls.io.SockelFactory
826,EMPTY
826,nidfs.datanode.parser.Sessionlmpl
826,mdfs.datanode.parser.ParserFactory
826,nldfs.LIUIs.parser.FileNameOperalions
826,rndfs.utils.parser.Parser
826,EMPTY
826,mdfs.datanode.io.Replicator
826,mdfs.datanode.io.NameNodelnformer
828,EMPTY
828,BaMeshL2PotocoI
828,MesbPoltDevlce
828,FoolleshL2Pio#ocol
828,EMPTY
828,WWINetDeve
828,EMPTY
828,"Mesh Wit MntetaceM.c"
828,EMPTY
828,"Mesh WifdnterfeI.cPI.gin"
828,EMPTY
866,"Base Scene"
866,SomeScene
876,"Drwer Class"
876,EMPTY
876,Queue
876,EMPTY
883,User
883,"Field Trip"
883,"Field Trip Report Item"
883,"Action Item"
883,Comment
883,Place
883,Anwser
883,Question
885,Bateria
885,Robot
885,"Mu n do Robot"
885,"E st ado Robot"
885,PincelAbajo
885,PincelArriba
885,"Cam in o"
894,"Ga m eAct ivity game Game"
894,Game
894,"Ga m eAtt rib Ut e playersArraylist<Players> getPlayersO Arraylist"
894,Memory
894,"Memo ryAtt rib Ut e s rows columns iiit getters settersint"
1598,"e SCModeI <V"
1598,"1nterface0 SCController"
1598,"9 SqiPhotoStorage"
1598,"e SCApplicatior"
1598,"interface*0 SCView <M"
1598,"0 MainController"
1598,"9 PhotoEntr"
1604,"0 LogSectionFragmentccm.CMPUT3O1F12TO7.crowdsource.tabviews"
1604,"0 DBHandler"
1604,"MyTasksSectionFragme I"
1604,"0 RecordAudioActivit"
1604,"G TakePhotoActivit"
1604,"0 ChoosePictureActivit I"
1604,EmailActivity
1604,"0 AddTaskActivit"
1605,EMPTY
1605,EMPTY
1605,transform
1605,"parser I"
1605,"ciatastore I"
1608,"Player id mt PlayerCursor PlayerC ) getters/setters removePlayerboolean updatePlayer"
1608,"Play e rL st instance PlayerList players ArrayList session ArrayList multiPlayerNetworkPlayer PlayerList getlnstance"
1608,"NetworkPlayer socket Socket hasToken boolean isAfk boolean"
1646,IndRelation
1646,QuickReductProcessor
1646,ApproximationSpace
1646,ReductProcessor
1646,UNKNOWNç
1654,specloader
1654,progmodel
1654,"S facetdecorator"
1654,runtirnecontext
1654,layout
1654,services
1654,facets
1654,"Tangle of 3specinteractions adapter"
1654,facetapi
1654,consent
1654,Sexceptions
1654,rnethodutds
1655,param
1655,EMPTY
1655,EMPTY
1655,metamodetvalidator.dflt
1656,about
1656,standard
1656,"— standard"
1656,EMPTY
1656,"S snapshot"
1657,"0 ConflgurationBuilderForWebapp"
1657,"0 ResourceServiet"
1657,"0 ForwardingServlet"
1659,fixtures
1659,value
1659,events
1659,"I clock"
1659,applib
1659,security
1659,adapters
1659,marker
1659,annotation
1659,"— snapshot"
1659,profiles
1659,query
1659,EMPTY
1659,EMPTY
1659,maybe
1659,EMPTY
1660,"IU factory"
1660,EMPTY
1660,ensure
1660,EMPTY
1660,autheiitication
1660,EMPTY
1660,matchers
1660,exceptoris
1660,"S debug"
1660,resource
1660,components
1660,encoding
1660,lang
1664,EMPTY
1664,EMPTY
1664,EMPTY
1664,movecursorop
1664,document
1664,EMPTY
1664,EMPTY
1664,EMPTY
1664,protocolhandler
1664,EMPTY
1664,obby
1664,protocol
1664,infinote
1664,wave
1666,"user interface"
1666,"domain layer"
1666,handlers
1666,operations
1666,user
1666,EMPTY
1666,"operatcon ‘."
1666,movecursorc
1666,"ocumenthandler I"
1666,insertop
1666,deleteop
1666,chunk
1666,protocolhandler
1666,"protocol layer"
1666,"session initiation"
1666,EMPTY
1666,EMPTY
1666,EMPTY
1666,wave
1666,"Iririspor1 layer"
1672,EMPTY
1672,EMPTY
1672,"Compon en"
1672,Queue
1672,Source
1672,Spitter
1672,Process
1674,"Decide personality and topic"
1674,"Refine the program"
1674,"High level testing"
1674,"Come up with phmases"
1674,"Des gn the algorithms todecide how the program isgoing to react"
1674,"Unit Testing and Debugging"
1674,=rrCODE==
1680,"Order Package"
1680,"Mailer Package"
1680,Resque
1680,OrderHandler
1680,UserSummaryController
1680,EMPTY
1680,UserSummaryMailer
1680,Order
1680,Databaselntertace
1680,LimitOrder
1680,MarketOrder
1680,StopOrder
1702,EMPTY
1702,Event
1702,Location
1702,Reminder
1703,LoginActivity
1703,"finishLogii• handleLogm• handleRegister• )ogm• onCreateOptonsMenu"
1703,"firnshRegister• handleRegister• onCreateOptionsMenu• register"
1703,StudentMainMenu
1703,"O MainMenu• onCreateOptionsMenu"
1703,"a fin ishAsynca getClasses• onCreateOptionsMenu• onWindowFocusChanged"
1704,"G Parent 7"
1704,"G MainMenu"
1704,"GClassesActivity I"
1704,"G InfractionsActivity I"
1704,"G LinkAccountsActivity"
1704,EMPTY
1704,"• finshAsync• onCreateOptaonsMenu• updateGrades"
1704,"AssignmentsActivity I"
1704,"G LocationsActivity"
1704,"f’wiishAsync• onCreateOptionsMenuA updateAssignments"
1704,"o mResponse String"
1704,"G GradesActivity"
1704,"• finhAsync• getstudent• onCreateOptionsMenu• onOptionsemSeiected"
1704,"G Assignment"
1704,"o rnAssignments ArrayListicAssignment>O mClassName StnngO mid mntO mSt8ffld kit"
1704,"G Grade"
1704,"E Grade.• getAssignmentName• getPomtsString"
1704,"E AssignmentE getAssgnments1S hackDate"
1705,"0 Student"
1705,"0 StudentMainMenu I"
1705,"G AssignmentsActivityfrishAsync• onCreateOpbonsMenuupdateAssignments"
1705,"O GradesActivity• rmshAsync• getStudent• onCreateOptionsMenu• onOptionsltemSelected"
1705,"0 ClassesActivity"
1705,"C? CourseO nissignments ArrayL5kAssignment>0? mClassName Strrngnd utmStaffid wit"
1705,"UNKNOWN1 Grade"
1705,"G Assignment0 mCourseI mtC rTesc StrWg ntueDate ‘TWnestampnid mtTiName StrWig rroiits doubleO. mTest booleanE AssignmentE getAssignmentsj hackDate"
1705,"E Grade• getAssignmentName• getPontsString"
1705,"0 GradeAdapter"
1705,"G AssignmentAdapterAssgnmentAdaptergetCountgettemgettemdgetViewsetGrades"
1706,"G Teecher 1A3Jore0J Te.cIJ• ddCIisi• QetCourscIt• tdateCssel"
1706,"GAddCIassActivty I"
1706,OClassesAty
1706,"Add StudentToClassActivky I"
1706,ModifyCIassActivy
1706,"AddinfractionActivity I"
1706,"Drn8hAsyncoP 9.tTn.St.mp• handIeSuC4Id• onCr..t.OpccsU.nuO"
1706,"0 Course"
1706,"A adAS• ardIeSub• onCreo.Opn.UenuO"
1706,"j Gradq• etAssimentNameO• Q.tPoi*sStxllg"
1706,"G Assignment"
1706,"0 Student"
1728,Tetromino
1728,GUI
1728,TetnsGameloop
1728,Board
1728,Menu
1740,"RobotObservable I"
1740,ObserverTty
1740,Robot
1769,Client
1769,<<bizCoCa
1769,<<bizUnit>>CategoryMgr
1769,<<sqiMap>>CategoryMgr.xsql
1769,<<table>>Category
1769,<<tabiTab
1778,EMPTY
1778,EMPTY
1778,EMPTY
1778,EMPTY
1778,EMPTY
1778,EMPTY
1778,EMPTY
1778,EMPTY
1778,EMPTY
1778,J
1778,EMPTY
1778,EMPTY
1778,EMPTY
1778,EMPTY
1778,EMPTY
1778,"tOdbI tOAM"
1778,EMPTY
1827,"cAd ministracion"
1827,EMPTY
1827,cAeropuerto
1827,Incidencia
1827,"Pa ra metro"
1827,Aeropuerto
1827,Vuelo
1827,Señalizer
1827,EMPTY
1827,EMPTY
1827,cReporte
1827,Escala
1827,EMPTY
1827,"Usua rio"
1827,Persona
1827,EMPTY
1827,Rol
1827,Contrasena
1827,Permiso
1827,cCliente
1827,SEirnulacion
1827,EMPTY
1827,AlgoritmosA
1827,cUsuarlo
1827,Pista
1833,EMPTY
1833,EMPTY
1833,EMPTY
1833,EMPTY
1835,ezcMvcMaiIRawRequest
1835,ezcMvcMaiIBugziIIaRequestFiIter
1835,ezcMvcMaiIRequestParser
1836,ezcPersistentObjectSchemaGenerator
1836,"ezcPersistentObjectTem plateSchemaWriterOptionsl"
1836,ezcPersistentObjectSchemaTemplateFunctions
1836,"ezcPersistentObjectTem plateSchemaWriter"
1837,ezcPhpGenerator
1837,ezcPhpGeneratorParameter
1837,"ezcPhpGeneratorRetu rn Data"
1838,"Reflection Property"
1838,ReflectionMethod
1838,"Reflection Parameter"
1838,"Ref lectionClass"
1838,ezcReflectionProperty
1838,ezcReflectionClass
1838,ezcRetlectionMethod
1838,"ezcReflection Parameter"
1838,ezcReflectionClassType
1838,<<interface>>ezcReflectionType
1838,ezcReflectionAbstractType
1838,"ezcReflectionPrimitiveType I"
1838,ezcReflectionArrayType
1838,ezcReflection
1838,EMPTY
1838,"getTypeByNamein type  stringsetTypeFactoryin factory ezcReflectionTypeFactory"
1839,ezcSearchDeIeteQuerySoIr
1839,ezcSearchDeleteQueryZendLucene
1839,"ezcSearch DeIeteQuII"
1839,ezcSearchQuery
1839,ezcSearchSession
1839,ezcSearchFindQuery
1839,ezcSearchZendLuceneHandIer
1839,ezcSearchQueryZendLucenej
1839,ezcSearchQuerySolr
1839,ezcSearchQueryBuilder
1839,"ezcSearch RstXmlExtractor"
1839,ezcSearchQueryToken
1839,ezcSearchlndexHandlerj
1839,ezcSearchSimplelmage
1839,ezcSearchQueryTools
1839,ezcSearchHandIer
1839,ezcSearchSimpleArticlej
1839,ezcSearchResult
1839,ezcSearchSolrHandler
1839,ezcSearchDefinitionDocumentField
1839,"ezcSearch Definition Provider"
1839,ezcSearchDocumentDefinition
1839,"ezcSearchDefinition Manager"
1839,"ezcSearchResultDocu ment"
1839,zcSearchEmbeddedManager
1839,ezcSearchXmlManagerj
1840,ezcSignalCollection
1840,"ezcSig nalCallbackCom parer"
1840,"ezcSig naiStaticCon nections"
1840,"ezcSig naiStaticCon nectionsBase"
1840,ezcSignalCollectionOptions
1841,"ezcSystem Info"
1841,ezcSystemInfoWindowsReader
1841,ezcSystemInfoMacReader
1841,L1ezcSystemlnfoReaderl
1841,ezcSystemInfoAcceIerator
1841,"ezcSystemlnfoFreeBsd Reader"
1841,"ezcSystemlnfoLin uxReader"
1842,"ezcAuthentication DatabaseFilter"
1842,ezcAuthenticationOpenidDbStore
1842,"ezcAuthenticationOpen id DbStoreOptions"
1842,ezcAuthenticationDatabaseOptions
1842,ezcAuthenticationDatabaselnfo
1843,"ezcTreeDbMaterialized Path"
1843,ezcTreeDbDataStore
1843,"#_c on stru ctØ"
1843,ezcTreeDbParentChild
1843,ezcTreeDb
1843,ezcTreeDbNestedSet
1844,"ezcTestRu n ner"
1844,ezcTestPrinterj
1844,"ezcTestReg ressionTest"
1844,ezcTestSettings
1844,"ezcTestReg ressionSu itej"
1844,ezcTestCase
1844,ezcTestlmageCase
1844,ezcTestConstraintSimilarlmage
1844,ezcTestDatabaseSettings
1845,ezclnputForm
1845,ezcInputFiIter
1845,ezcInputFormDefinitionEIement
1846,ezcBase
1846,ezcBasePersistable
1846,ezcBaseMetaDataPearReader
1846,"ezcBaseln it"
1846,ezcBaseOptions
1846,ezcBaseMetaData
1846,"ezcBaseConfig u ration Initializer"
1846,ezcBaseAutoloadOptions
1846,ezcBaseStruct
1846,"ezcBaseFeatu res"
1846,ezcBaseFiIeFindContext
1846,ezcBaseRepositoryDirectory
1846,ezcBaseMetaDataTarballReader
1846,ezcBaseFile
1846,"ezcBaseExportabIeI setstateØ"
1847,<UlApplicationDelegate>
1847,AppDelegate
1847,ApplicaitonData
1847,Catagory
1847,Event
1847,Attraction
1850,Picker
1850,Pick_EM
1850,"I m Corr"
1850,DoG
1850,"PickFra me"
1850,DilateDiff
1850,PickPanel
1850,About
1850,PanelDoG
1850,PanelDilateDiff
1850,PanellmCorr
1850,FFTMath
1850,Attributes
1850,"T0C SV"
1850,AlgoFactory
1850,"Crop per"
1850,InfoHeip
1851,ezcConfiguration
1851,ezcConfigurationManager
1851,"ezcConfig u rationWriter"
1851,ezcConfigurationlniWriter
1851,"ezcConfig u ration FileWriter"
1851,ezcConfigurationArrayWriter
1851,"ezcConfiguration FiIeReader"
1851,ezcConfigurationlniReaderj
1851,ezcConfigurationIniParser
1851,"ezcConfig u ration Reader"
1851,"ezcConfig u rationArrayReader"
1851,ezcConfigurationlniltem
1851,"ezcConfig u rationVal idation Result 1"
1851,ezcConfigurationValidationltem
1853,Engine
1853,Scene
1853,Entity
1853,"Eng in eManag er"
1853,"B eh avior"
1853,"Corn ponent"
1855,ezcDebug
1855,"ezcDebugVariableDumpToold urn pVari ab I e c utStri n g d urn pArrayOdumpObjectOdump ResourceOgetPropertyValueOgetPropertyVisibiIity"
1855,ezcDebugSwitchTimerStruct
1855,ezcDebugTimerStruct
1855,ezcDebugXdebugStacktraceIterator
1855,"ezcDebug Ph pStacktracelteratorj"
1855,ezcDebugHtmIFormatter
1855,ezcDebugTimer
1855,ezcDebugStacktracelteratorj
1855,ezcDebugOutputFormatterj
1855,"ezcDebugStructu re"
1855,ezcDebugMemoryWriter
1855,ezcDebugOptions
1856,ezclmageHandler
1856,ezcImageGdBaseHandIer
1856,"ezclmageConverter 1"
1856,ezclmageTransformation
1856,ezcImageMethodcaIIHandIer
1856,ezcImageImagemagickBaseHandIer
1856,ezclmageGeometryFilters
1856,ezclmageHandlerSettingsj
1856,ezclmageGdHandler
1856,ezcImageConverterSettings
1856,constructO
1856,"ezclmagelmagemagickHandler1#getDirectionModifierHborderocolorspaceOcrop1 croppedThumbnailOfilledThumbnailOjnoiseoHscaIeOjscaleExactOscaleHeightO1 scalePercentOIscalewidthOIswirIO1 IwatermarkAbsoluteO1 IwatermarkPercentO"
1856,ezcImageSaveOptions
1856,ezcImageFiIter
1856,ezcImageThumbnaiIFiIters
1856,ezcImageWatermarkFiIters
1856,ezcImageEffectFiIters
1856,ezclmageColorspaceFilters
1892,"Ben utzer"
1892,Hersteller
1892,Erfahrungsbericht
1892,Wirkstoff
1892,Verschreibung
1892,"Med ikamente"
1892,Patient
1892,Lieferant
1900,"<<Interfa Ce>>Item Renderer"
1900,"C ate o ryE d ito"
1900,<<Interface>>Category
1900,"<<Interfa Ce>>Item"
1900,EMPTY
1900,HierarchyNavigato
1900,AtctCatego
1900,Hierarchyltem
1900,"<<Interfa Ce>>Hierarchy"
1900,xisCategor
1900,SIicerCategor
1900,Navigator
1900,"<<Interface>>Tree Model"
1900,TreeModeIAdapte
1900,MemberNavigato
1921,Person
1921,Address
1921,Hospital
1921,Notification
1921,User
1921,Drugstore
1921,SystemTrigger
1921,EMPTY
1921,Healthlnsurance
1921,Pharmacist
1921,Patient
1921,Nurse
1921,Doctor
1921,NotoficaitonView
1921,"NotiticationControll e r"
1921,"OrderQueueContro lie r"
1921,TimeRange
1921,PrescriptionController
1921,interface>>Queue
1921,Pickup
1921,Prescription
1921,Medicament
1921,enumeration>OrderState
1921,Order
1921,"enumeration>AnalysisCatego r"
1921,Analysis
1921,AnalysisState
1921,"AnalysisControl le r"
1921,AnalysisView
1921,AnalysisExecution
1921,AnalysisQuestion
1923,EMPTY
1923,"C ate o ryE d ito"
1923,Categoy1l&de?
1923,EMPTY
1923,EMPTY
1923,EMPTY
1923,EMPTY
1937,"Resource Model Loader"
1937,"StreamModelLoad e r"
1937,"File ModelLoader"
1937,"<<interface>>P rot ile M o d e ILo a d e r"
1937,"<<interface>>Profile Man a 9 e"
1937,ZipModelLoader
1937,JavaProlile
1937,"JavaFormatingStrate y"
1937,EMPTY
1937,Project
1937,"P rof ile C o nf ig U ratio n"
1937,JavaBeansProfile
1937,UserDefinedProfile
1937,<<interface>>FormatingStrategy
1942,"Class Diagram 021012"
1942,User
1942,Calendar
1942,Message
1942,Event
1942,Invitation
1942,DatabaseObject
1942,<<enum>>Response
1943,Compas
1943,aistandSensoren
1943,Led
1943,Motor
1943,Control
1943,EMPTY
1948,"Ant B rain"
1950,<UlApplicationDelegate>
1950,UlResponder
1950,XMLParsingDelegate
1950,<NSXMLParserDelegate>
1950,AppDelegate
1950,UlTabBarController
1950,NearMeViewController
1950,BrowseViewController
1950,"Events ViewController"
1950,FavouritesViewController
1950,AppData
1950,"Cata gory"
1950,CatagoryDetailViewController
1950,Event
1950,Attraction
1950,AttractionDetailViewController
1950,EventsDetailViewController
1950,Location
1950,MKMapViewDelegate
1950,HorizontalMapViewController
1950,<MKMapViewDelegate>
1957,Polygon
1957,Point
1957,MapParams
1957,TimeLine
1957,EMPTY
1957,ChangePolygon
1957,MovingPolygon
1957,Polyline
1957,Object
1957,EMPTY
1957,Map
1957,ViewController
1957,Teacher
1957,Student
1957,Picture
1957,SVOObject
1957,AuthorizationService
1957,Parser
1957,ObjectDAO
1957,Storage
1957,File
1975,"<<Java Class>>G CategoriesManager"
1975,"<<Java Class>>0 Add PolActivitygeco9.actJdft"
1975,"<<Java Class>>PoiListManagerge9.a.wIt"
1975,"<<Java Class>>GSuggestionco.goog.do’ o"
1975,"<Java Class>>PôlAugmentedRealityManagerçoog.actte"
1975,"<<Java Class>>G Poir.lapManagergec4O9.act. t"
1975,"<<Java Class>>Poi Sea rchActivity"
1975,"<Java Class>>PoJstResponsecom.go9.don"
1975,"<<Java Cesettinggecg.a"
1975,"<<Java Class>>GCategorycorn .gec4og .dornin"
1975,"<<Java Class>>ØPoicomgeøIogdom"
1975,"<<Ja Class>>Baseesponsecorn. g Ofl1"
1975,"<<Java Class>>0 ResourceTypecom.geoo9 don"
1975,"<<Java Class>>O Resourcecorn .geolog .dornino"
1975,"<<Java Class>>0 GeologActivity"
1975,"<<Java Class>>ConfnmResponseo.’.veb"
1975,"<<Java Class>>CategoryListResponsecom.gecog.doniin.wet"
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1983,EMPTY
1994,Simulation
1994,Domain
1994,Boundaries
1994,Elements
1994,Nodes
1994,Quadrilaterals
1994,Triangles
1994,DOF
1994,Lines
1994,Region
2000,diseases.php
2000,edqe.php
2000,ontoloqyterms.php
2000,treescnptphp
2000,tree.html
2000,phenotypes.php
2016,SkinObserverController
2016,"interface’0 FController"
2016,"interface’0 DatabaseModelinterface"
2016,"DatabaseModelcm put3OlWl 2.android.m ode I"
2019,Acount
2019,CNPCIient
2019,CNPServer
2019,SessionUser
2019,Session
2019,SessionLeader
2039,BulidOrder
2039,Buildltem
2039,Race
2039,Unit
2039,Building
2039,Upgrade
2048,EMPTY
2048,EMPTY
2048,EMPTY
2048,EMPTY
2048,EMPTY
2048,EMPTY
2048,EMPTY
2048,EMPTY
2048,EMPTY
2048,EMPTY
2050,Person
2050,Trip
2050,Location
2050,participations
2050,Response
2050,Search
2050,Modality
2050,Preferences
2107,"<<Java Class’>3 C ameraManaçjerTestserw isapazaow CameraSerice_II PR tests"
2107,"<<Java C lass’>OMamserwisaparatow .CameraSerAce_I.I PP"
2107,"<<Java C lass’>G PersonManagerTestserw isapazaow CameraSerice_II PR tests"
2107,"dtvlainGm ainString"
2107,"<<Java Class’>G C ameraManagerserwisaparatow .CameraSerice_LI PR.manager"
2107,"<<Java Class>>G PersoliManagerserwisaparatow .CameraSerice_II PR.manager"
2107,"UNKNOWNft ameratvlanager(o addC ameraCamerabooIeano rem oveC am eraC am era0 getiIOLi<Camera>"
2107,"PersonManager0 addP ersonP ersono rem oveP ersonP erson0 getiILi<Person"
2107,"<<Java Class>>Databaseserwisaparatow .CameraSerice_II PR.database"
2112,"GAL OrderedCrossover"
2112,GAL_ClassicCrossover
2112,GAL_RandomCrossover
2112,GAL_Crosoits
2112,"GAL MultiPointCrossover"
2112,GAL_SegmentCrossover
2112,GAL_UniformCrossover
2186,GAL_GeneConfig
2186,EMPTY
2186,GAL_NominalGeneConfig
2186,"GAL BinaryGeneConfig"
2186,GAL_DoubIe3eneConfig
2186,GAL_CharacterGeneConfig
2187,GAL_Interlace
2187,EMPTY
2187,GAL_Configuration
2187,"GAL_ GeneticOpero.tor"
2187,GAL_GUI
2187,GAL_Gene
2187,GAL_TerminczrioitCondition
2187,GAL_ChromosomeConfig
2187,GAL_NaturalSelector
2187,GAL_FititessFunction
2187,GAL_GenConfig
2187,GAL_Initializer
2188,GAL_ClassicMutation
2188,"GAL SwapMutation"
2188,GAL_ShuffleMutation
2188,GAL_GeneticOperator
2188,GAL_Inversion
2188,GAL_ChromosomeMutation
2188,GAL_Crossovei
2189,"GAL_C IassicHancfler"
2189,GAL_Handles
2189,GAL_ModHancfIer
2227,Recordatorlo
2227,Info_Gen
2227,"Aná I isis"
2227,Peso_Ideal
2227,Paciente
2227,Dietista
2227,"S em a na rio"
2227,Antrop_Nec
2227,Trat_Apoyo
2227,Enfermedad
2227,Diarlo_Dietetico
2227,"Ingrediente I"
2227,Receta
2237,GAL_TournamentSelector
2237,"GAL ElitistSelector"
2237,"GAL_ClassicRanking Selector"
2237,"GAL_LinealRanking Selector"
2237,GAL_NaturalSelector
2237,"GAL_Ran kingSelector"
2237,GAL_NonLineaIRankingSeIector
2237,GAL_RouletteSelector
2255,Carta
2255,EMPTY
2255,Jugador
2255,EMPTY
2255,JuegoPoker
2255,BarajaFrancesa
2255,JugadorPoker
2268,EMPTY
2268,EMPTY
2268,EMPTY
2268,EMPTY
2289,"<<Java Class>>MemoDiaIocon.haJIauniv.daIog"
2289,"<<Java Class>>G TabIeDiaIocom.halauniv.dialcg"
2289,"<<Java Class>>MapDialogcom.halauniv.dialog"
2289,"<<Java Class>>AIertDiaIogcon.halauniv.dialog"
2289,"<<Java Class>>ViewPickDialoqcon.haIauniv.diaIog"
2289,"<<Java Class>>MenuDialoqcon.haJIauniv.daIog"
2289,"<<Java Class>>ChatDiaIoqconi.halauniv.dialog"
2289,"JViewPickDialog• onCreateBundle• onDestroyOvoid"
2289,"<<Java Class>>ØReceiverconi.hallauniv.dialog"
2289,"<<Java Class>>NumPickerDialoqcon.haIauniv.diaIog"
2289,"<<Java Class>>DataListAdapterMenucom.halauniv.dialcg"
2289,"<<Java Class>>eConnectChatTaskcom.haltauniv.dialog"
2289,"<<Java Class>>e chatTh readcoI1 .halauniv.dialog"
2289,"EReceiver• onReceiveCoritextInterit"
2289,"ENumPickerDialogoG onCreateBundIevod"
2289,"EconnectChatTaskG oriPreExecutevoidG dolnBackgroundStringfl"
2289,"<<Java Class>>MenuHolderconthallauniv.dialog"
2292,Session
2292,Game
2292,Bike
2292,GUI
2294,€DarabaseObJechu.documaison.data.entities
2294,Documenthu.documaison.data.entities
2294,DocumentTypehudocumaison.data.entities
2294,"DocumentTagConnectionhudocumsison. data.entities"
2294,"GMetadatahu. documaison.data.entities"
2294,OCommenthudocumaison.data.entities
2294,"hu. documaison.data.entities"
2295,"GjDarabaseObjecrhu. documaison. data. entities"
2295,"G DocumentTypehudocurnaison. data.entities"
2295,"DefaultMetadatahu. documaison. data. entities"
2295,Documenthudocumaison.data.entities
2302,EMPTY
2302,c<Intecface>>View
2302,EMPTY
2302,FIoorV1w
2302,ResetButton
2302,Handler
2302,EIvatorVIew
2302,HandIer4
2302,EngInGTGstView
2302,JFramoViw
2302,FloorListVlew
2302,HandIer3
2302,Handler2
2302,EMPTY
2302,EMPTY
2302,EMPTY
2304,"inter1ce0 DataOutputExtended"
2304,"inter1ce0 DatainputExtended"
2304,"e FieldType T"
2304,"e DatalnputStreamExtended"
2304,"G DatainputExtendedDecorator I"
2304,"0 DataOutputStreamExtended"
2304,"G DataOutputExtendedDecorator I"
2304,"G DebugDatalnputExtended I"
2304,"G DebuqDataOutpiitExtended I"
2304,"interface0 Encodable"
2305,GjAbsrracrMeraclaahudocumaison.data.entities
2305,"DefaultMetadatahu. documaison. data. entities"
2305,"GMetadatahu. documaison.data.entities"
2305,DocumentTypehudocumaison.data.entities
2305,Documenthudocumaison.data.entities
2305,"DocumentTagConnectionhudocumsison. data.entities"
2305,OCommenthudocumaison.data.entities
2305,"hu. documaison.data.entities"
2308,PYDWGN
2308,Ward
2308,Graffiti
2308,Comment
2308,Vote
2314,Data_Transfer_Manager
2314,Physics_A
2315,Client
2315,Evaluator
2315,EMPTY
2315,Parser
2315,Command
2315,CommandFactoty
2315,Operator
2315,Number
2315,Parentheses
2315,LeftParentheses
2315,RightParentheses
2315,EMPTY
2315,"Optim izedFactory"
2315,BasicFactory
2315,Add
2315,Subtract
2315,Multiply
2315,"r1odu lus"
2315,Exponent
2315,Divide
2316,"NOTE1. Relations between business logicand persistent object were notmarked in the diagram.2. Classes with yellow background are not actuallyphp classes but common php script files.3. The brief order of dependency in add.phpand edit.php has been mark"
2316,ezcomFormTool
2316,ezcomAddCommentTool
2316,ezcomEditCommertTooI
2316,EMPTY
2316,ezcomCookieManger
2316,edit.php
2316,ezcomCommentManager
2316,"ezcomPermi ss ion"
2316,delete.php
2316,ezcomUtility
2316,ezcomCommonCommentManager
2316,ezcomSubscriptionManager
2316,activate.php
2316,cronjob—ezcomclearsubscription.php
2316,eZPersistentObject
2316,cronjob—ezcomhandlenotification.php
2316,ezcomNotificationManager
2316,ezcomComment
2316,ezcomSubscriber
2316,ezcomSubscription
2316,ezcomNotification
2316,ezcomNotificationEmaAlManager
2331,EMPTY
2331,EMPTY
2331,EMPTY'